/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAPS;

import DAO.DAOClientes;
import DAO.DAOFilmes;
import DAO.DAOFilmesAlugados;
import DAO.DAOUsuarios;
import Modelos.Clientes;
import Modelos.Filmes;
import Modelos.FilmesAlugados;
import Modelos.Usuarios;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class LocadoraDeFilmes extends javax.swing.JFrame {

    /**
     * Creates new form LocadoraDeFilmes
     */
    public LocadoraDeFilmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JpHome = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnAlugarFilme = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrarCliente = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCadastrarUsuario = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnCadastrarFilme = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnSair = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JpAlugar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textFilme = new javax.swing.JTextField();
        FilmesAlugadosButton = new javax.swing.JButton();
        filmesButton = new javax.swing.JButton();
        alugarButton = new javax.swing.JButton();
        textData = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JpCadCli = new javax.swing.JPanel();
        ClienteCadastroButton = new javax.swing.JButton();
        ClientesCadastradosButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        JpCadUsu = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        UsuarioCadastroButton = new javax.swing.JButton();
        UsuariosCadastradosButton = new javax.swing.JButton();
        JpCadFil = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        FilmesCadastroButton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JpHome.setBackground(new java.awt.Color(255, 255, 255));
        JpHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(24, 25, 30));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(24, 25, 30));
        Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Locadora");
        Titulo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Pedro\\Desktop\\Dev\\APS\\APS_TerceiroSemestre2021\\LocadoraAps\\IconsAPS\\play\\1x\\baseline_play_arrow_white_36dp.png")); // NOI18N
        Titulo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 40));

        sidepane.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 228, 90));

        btnAlugarFilme.setBackground(new java.awt.Color(163, 64, 64));
        btnAlugarFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlugarFilmeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlugarFilmeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlugarFilmeMouseExited(evt);
            }
        });
        btnAlugarFilme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alugar um filme");
        btnAlugarFilme.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 123, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Pedro\\Desktop\\Dev\\APS\\APS_TerceiroSemestre2021\\LocadoraAps\\IconsAPS\\movie\\1x\\baseline_movie_white_24dp.png")); // NOI18N
        btnAlugarFilme.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        sidepane.add(btnAlugarFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 50));

        btnCadastrarCliente.setBackground(new java.awt.Color(247, 230, 230));
        btnCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarClienteMouseExited(evt);
            }
        });
        btnCadastrarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel11.setText("Cadastrar um cliente");
        btnCadastrarCliente.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Pedro\\Desktop\\Dev\\APS\\APS_TerceiroSemestre2021\\LocadoraAps\\IconsAPS\\plus\\1x\\baseline_add_black_18dp.png")); // NOI18N
        btnCadastrarCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        sidepane.add(btnCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 50));

        btnCadastrarUsuario.setBackground(new java.awt.Color(247, 230, 230));
        btnCadastrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarUsuarioMouseExited(evt);
            }
        });
        btnCadastrarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Cadastrar um usuário");
        btnCadastrarUsuario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Pedro\\Desktop\\Dev\\APS\\APS_TerceiroSemestre2021\\LocadoraAps\\IconsAPS\\plus\\1x\\baseline_add_black_18dp.png")); // NOI18N
        btnCadastrarUsuario.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        sidepane.add(btnCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 50));

        btnCadastrarFilme.setBackground(new java.awt.Color(247, 230, 230));
        btnCadastrarFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarFilmeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarFilmeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarFilmeMouseExited(evt);
            }
        });
        btnCadastrarFilme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel13.setText("Cadastrar um filme");
        btnCadastrarFilme.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Pedro\\Desktop\\Dev\\APS\\APS_TerceiroSemestre2021\\LocadoraAps\\IconsAPS\\plus\\1x\\baseline_add_black_18dp.png")); // NOI18N
        btnCadastrarFilme.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        sidepane.add(btnCadastrarFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 50));

        btnSair.setBackground(new java.awt.Color(163, 64, 64));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SAIR");
        btnSair.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Pedro\\Desktop\\Dev\\APS\\APS_TerceiroSemestre2021\\LocadoraAps\\IconsAPS\\exit\\1x\\baseline_close_black_24dp.png")); // NOI18N
        btnSair.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 50));

        sidepane.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 210, 50));

        JpHome.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 560));

        jPanel3.setBackground(new java.awt.Color(237, 17, 17));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        JpHome.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 10));

        JpAlugar.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(163, 64, 64));
        jLabel5.setText("ALUGAR FILME");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(24, 25, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(160, 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(24, 25, 30));
        jLabel6.setText("Filme Alugado");

        FilmesAlugadosButton.setBackground(new java.awt.Color(255, 255, 255));
        FilmesAlugadosButton.setForeground(new java.awt.Color(24, 25, 30));
        FilmesAlugadosButton.setText("Controle de Filmes Alugados");
        FilmesAlugadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmesAlugadosButtonActionPerformed(evt);
            }
        });

        filmesButton.setBackground(new java.awt.Color(255, 255, 255));
        filmesButton.setForeground(new java.awt.Color(24, 25, 30));
        filmesButton.setText("Filmes Disponiveis");
        filmesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmesButtonActionPerformed(evt);
            }
        });

        alugarButton.setBackground(new java.awt.Color(255, 255, 255));
        alugarButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        alugarButton.setForeground(new java.awt.Color(163, 64, 64));
        alugarButton.setText("Alugar");
        alugarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alugarButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(24, 25, 30));
        jLabel14.setText("Cliente");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(24, 25, 30));
        jLabel15.setText("Data de alocação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alugarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(FilmesAlugadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filmesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(alugarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FilmesAlugadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filmesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpAlugarLayout = new javax.swing.GroupLayout(JpAlugar);
        JpAlugar.setLayout(JpAlugarLayout);
        JpAlugarLayout.setHorizontalGroup(
            JpAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAlugarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JpAlugarLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpAlugarLayout.setVerticalGroup(
            JpAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAlugarLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        JpHome.add(JpAlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 790, -1));

        JpCadCli.setBackground(new java.awt.Color(255, 255, 255));
        JpCadCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClienteCadastroButton.setBackground(new java.awt.Color(255, 255, 255));
        ClienteCadastroButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ClienteCadastroButton.setForeground(new java.awt.Color(163, 64, 64));
        ClienteCadastroButton.setText("Cadastrar");
        ClienteCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteCadastroButtonActionPerformed(evt);
            }
        });
        JpCadCli.add(ClienteCadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 190, 40));

        ClientesCadastradosButton.setBackground(new java.awt.Color(255, 255, 255));
        ClientesCadastradosButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ClientesCadastradosButton.setForeground(new java.awt.Color(24, 25, 30));
        ClientesCadastradosButton.setText("Clientes Cadastrados");
        ClientesCadastradosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesCadastradosButtonActionPerformed(evt);
            }
        });
        JpCadCli.add(ClientesCadastradosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 190, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(163, 64, 64));
        jLabel7.setText("CADASTRAR CLIENTES");

        jPanel6.setBackground(new java.awt.Color(24, 25, 30));
        jPanel6.setPreferredSize(new java.awt.Dimension(160, 4));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JpCadCli.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 320, 80));

        JpHome.add(JpCadCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 790, 550));

        JpCadUsu.setBackground(new java.awt.Color(255, 255, 255));
        JpCadUsu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(163, 64, 64));
        jLabel8.setText("CADASTRAR USUÁRIOS");

        jPanel8.setBackground(new java.awt.Color(24, 25, 30));
        jPanel8.setPreferredSize(new java.awt.Dimension(160, 4));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JpCadUsu.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 330, 80));

        UsuarioCadastroButton.setBackground(new java.awt.Color(255, 255, 255));
        UsuarioCadastroButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        UsuarioCadastroButton.setForeground(new java.awt.Color(163, 64, 64));
        UsuarioCadastroButton.setText("Cadastrar");
        UsuarioCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCadastroButtonActionPerformed(evt);
            }
        });
        JpCadUsu.add(UsuarioCadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 190, 40));

        UsuariosCadastradosButton.setBackground(new java.awt.Color(255, 255, 255));
        UsuariosCadastradosButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        UsuariosCadastradosButton.setForeground(new java.awt.Color(24, 25, 30));
        UsuariosCadastradosButton.setText("Usuários Cadastrados");
        UsuariosCadastradosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosCadastradosButtonActionPerformed(evt);
            }
        });
        JpCadUsu.add(UsuariosCadastradosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 190, 40));

        JpHome.add(JpCadUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 790, 550));

        JpCadFil.setBackground(new java.awt.Color(255, 255, 255));
        JpCadFil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(163, 64, 64));
        jLabel16.setText("CADASTRAR FILMES");

        jPanel10.setBackground(new java.awt.Color(24, 25, 30));
        jPanel10.setPreferredSize(new java.awt.Dimension(160, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JpCadFil.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 320, 80));

        FilmesCadastroButton.setBackground(new java.awt.Color(255, 255, 255));
        FilmesCadastroButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        FilmesCadastroButton.setForeground(new java.awt.Color(163, 64, 64));
        FilmesCadastroButton.setText("Cadastrar");
        FilmesCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmesCadastroButtonActionPerformed(evt);
            }
        });
        JpCadFil.add(FilmesCadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 197, 39));

        JpHome.add(JpCadFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 790, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpHome, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpHome, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FilmesAlugadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmesAlugadosButtonActionPerformed
        ListaFilmesAlugados listaFilmesAlugados = new ListaFilmesAlugados(); 
        listaFilmesAlugados.setLocationRelativeTo(null);
        listaFilmesAlugados.setVisible(true);
        JpAlugar.setVisible(true);
        JpCadCli.setVisible(false);
        JpCadFil.setVisible(false);
        JpCadUsu.setVisible(false);
    }//GEN-LAST:event_FilmesAlugadosButtonActionPerformed

    private void alugarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alugarButtonActionPerformed
        FilmesAlugados f = new FilmesAlugados();
            f.setNome(textNome.getText());
            f.setDVDnome(textFilme.getText());
            f.setDataAlocacao(textData.getText());
            
            DAOFilmesAlugados filmesalugados = new DAOFilmesAlugados();
            filmesalugados.RegistroFilmesAlugados(f);
            
            JOptionPane.showMessageDialog(null, "Filme alugado por "+textNome.getText());
            
            textNome.setText("");
            textFilme.setText("");
            textData.setText("");
            
    }//GEN-LAST:event_alugarButtonActionPerformed

    private void filmesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmesButtonActionPerformed
        ListaFilmes listafilmes = new ListaFilmes();
        listafilmes.setLocationRelativeTo(null);
        listafilmes.setVisible(true);
        JpAlugar.setVisible(true);
        JpCadCli.setVisible(false);
        JpCadFil.setVisible(false);
        JpCadUsu.setVisible(false);
    }//GEN-LAST:event_filmesButtonActionPerformed

    private void btnAlugarFilmeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlugarFilmeMouseEntered
        // TODO add your handling code here:
        btnAlugarFilme.setBackground(Color.decode("#7a3232"));
    }//GEN-LAST:event_btnAlugarFilmeMouseEntered

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnAlugarFilmeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlugarFilmeMouseExited
        // TODO add your handling code here:
        btnAlugarFilme.setBackground(Color.decode("#a34040"));    
    }//GEN-LAST:event_btnAlugarFilmeMouseExited

    private void btnCadastrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarClienteMouseEntered
        // TODO add your handling code here:
        btnCadastrarCliente.setBackground(Color.decode("#ded9d9"));
    }//GEN-LAST:event_btnCadastrarClienteMouseEntered

    private void btnCadastrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioMouseEntered
        // TODO add your handling code here:
        btnCadastrarUsuario.setBackground(Color.decode("#ded9d9"));
    }//GEN-LAST:event_btnCadastrarUsuarioMouseEntered

    private void btnCadastrarFilmeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarFilmeMouseEntered
        // TODO add your handling code here:
       btnCadastrarFilme.setBackground(Color.decode("#ded9d9")); 
    }//GEN-LAST:event_btnCadastrarFilmeMouseEntered

    private void btnCadastrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarClienteMouseExited
        // TODO add your handling code here:
        btnCadastrarCliente.setBackground(Color.decode("#f7e6e6"));
    }//GEN-LAST:event_btnCadastrarClienteMouseExited

    private void btnCadastrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioMouseExited
        // TODO add your handling code here:
        btnCadastrarUsuario.setBackground(Color.decode("#f7e6e6"));
    }//GEN-LAST:event_btnCadastrarUsuarioMouseExited

    private void btnCadastrarFilmeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarFilmeMouseExited
        // TODO add your handling code here:
        btnCadastrarFilme.setBackground(Color.decode("#f7e6e6"));
    }//GEN-LAST:event_btnCadastrarFilmeMouseExited

    private void ClienteCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteCadastroButtonActionPerformed
        String nome,telefone,cpf;
        nome = JOptionPane.showInputDialog(null, "Digite o nome do cliente: ");
        telefone = JOptionPane.showInputDialog(null, "Digite o telefone do cliente: ");
        cpf = JOptionPane.showInputDialog(null, "Digite o CPF do cliente: ");

        Clientes c = new Clientes();
        c.setNome(nome);
        c.setTelefone(telefone);
        c.setCpf(cpf);

        DAOClientes cliente = new DAOClientes();
        cliente.inserirClientes(c);

        JOptionPane.showMessageDialog(null, "Cliente "+nome+" Cadastrado!");
    }//GEN-LAST:event_ClienteCadastroButtonActionPerformed

    private void ClientesCadastradosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesCadastradosButtonActionPerformed
        ListaClientes lista = new ListaClientes();
        lista.setLocationRelativeTo(null);
        lista.setVisible(true);
        JpAlugar.setVisible(false);
        JpCadCli.setVisible(true);
        JpCadFil.setVisible(false);
        JpCadUsu.setVisible(false);
    }//GEN-LAST:event_ClientesCadastradosButtonActionPerformed

    private void UsuarioCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCadastroButtonActionPerformed
        String nomeusuario,telefoneusuario,cpfusuario;
        nomeusuario = JOptionPane.showInputDialog(null, "Digite o nome do usuario: ");
        telefoneusuario = JOptionPane.showInputDialog(null, "Digite o telefone do usuario: ");
        cpfusuario = JOptionPane.showInputDialog(null, "Digite o CPF do usuario: ");

        Usuarios u = new Usuarios();
        u.setNomeUsuario(nomeusuario);
        u.setTelefoneUsuario(telefoneusuario);
        u.setCpfUsuario(cpfusuario);

        DAOUsuarios usuario = new DAOUsuarios();
        usuario.cadastrarUsuario(u);

        JOptionPane.showMessageDialog(null, "Usuario "+nomeusuario+" Cadastrado!");
    }//GEN-LAST:event_UsuarioCadastroButtonActionPerformed

    private void UsuariosCadastradosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosCadastradosButtonActionPerformed
        ListaUsuarios listaUser = new ListaUsuarios();
        listaUser.setLocationRelativeTo(null);
        listaUser.setVisible(true);
        JpAlugar.setVisible(false);
        JpCadCli.setVisible(false);
        JpCadFil.setVisible(false);
        JpCadUsu.setVisible(true);
    }//GEN-LAST:event_UsuariosCadastradosButtonActionPerformed

    private void FilmesCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmesCadastroButtonActionPerformed
        String nomefilme, secao, duracao;

        nomefilme = JOptionPane.showInputDialog(null, "Digite o nome do filme: ");
        secao = JOptionPane.showInputDialog(null, "Digite a seção do filme: ");
        duracao = JOptionPane.showInputDialog(null, "Digite a duração do filme: ");

        Filmes f = new Filmes();
        f.setNomeFilme(nomefilme);
        f.setSecao(secao);
        f.setDuracao(duracao);

        DAOFilmes filme = new DAOFilmes();
        filme.RegistroFilmes(f);

        JOptionPane.showMessageDialog(null, "Filme "+nomefilme+" Registrado!");

    }//GEN-LAST:event_FilmesCadastroButtonActionPerformed

    private void btnAlugarFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlugarFilmeMouseClicked
        // TODO add your handling code here:
        JpAlugar.setVisible(true);
        JpCadCli.setVisible(false);
        JpCadFil.setVisible(false);
        JpCadUsu.setVisible(false);
    }//GEN-LAST:event_btnAlugarFilmeMouseClicked

    private void btnCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarClienteMouseClicked
        // TODO add your handling code here:
        JpAlugar.setVisible(false);
        JpCadCli.setVisible(true);
        JpCadFil.setVisible(false);
        JpCadUsu.setVisible(false);
    }//GEN-LAST:event_btnCadastrarClienteMouseClicked

    private void btnCadastrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioMouseClicked
        // TODO add your handling code here:
        JpAlugar.setVisible(false);
        JpCadCli.setVisible(false);
        JpCadFil.setVisible(false);
        JpCadUsu.setVisible(true);
    }//GEN-LAST:event_btnCadastrarUsuarioMouseClicked

    private void btnCadastrarFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarFilmeMouseClicked
        // TODO add your handling code here:
        JpAlugar.setVisible(false);
        JpCadCli.setVisible(false);
        JpCadFil.setVisible(true);
        JpCadUsu.setVisible(false);
    }//GEN-LAST:event_btnCadastrarFilmeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocadoraDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocadoraDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocadoraDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocadoraDeFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocadoraDeFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClienteCadastroButton;
    private javax.swing.JButton ClientesCadastradosButton;
    private javax.swing.JButton FilmesAlugadosButton;
    private javax.swing.JButton FilmesCadastroButton;
    private javax.swing.JPanel JpAlugar;
    private javax.swing.JPanel JpCadCli;
    private javax.swing.JPanel JpCadFil;
    private javax.swing.JPanel JpCadUsu;
    private javax.swing.JPanel JpHome;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton UsuarioCadastroButton;
    private javax.swing.JButton UsuariosCadastradosButton;
    private javax.swing.JButton alugarButton;
    private javax.swing.JPanel btnAlugarFilme;
    private javax.swing.JPanel btnCadastrarCliente;
    private javax.swing.JPanel btnCadastrarFilme;
    private javax.swing.JPanel btnCadastrarUsuario;
    private javax.swing.JPanel btnSair;
    private javax.swing.JButton filmesButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textFilme;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
